# Generated by Django 5.1.2 on 2024-11-23 22:30

import django.core.validators
import django.db.models.deletion
import label_music_manager.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('artist', models.CharField(max_length=512)),
                ('cover_image', models.ImageField(blank=True, default='no_cover.jpg', null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)])),
                ('format', models.CharField(choices=[('DD', 'Digital Download'), ('CD', 'CD'), ('VL', 'Vinyl')], max_length=512)),
                ('release_date', models.DateField(blank=True, null=True, validators=[label_music_manager.validators.dateValidator])),
                ('slug', models.SlugField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='MusicManagerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=512)),
                ('role', models.CharField(choices=[('Artist', 'Artist'), ('Editor', 'Editor'), ('Viewer', 'Viewer')], max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumTrackListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_music_manager.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_music_manager.song')),
            ],
            options={
                'ordering': ['album', 'position'],
                'unique_together': {('album', 'song')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(related_name='albums', through='label_music_manager.AlbumTrackListItem', to='label_music_manager.song'),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'artist', 'format')},
        ),
    ]
