# Generated by Django 5.1.2 on 2024-11-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicmanageruser',
            options={'permissions': [('artist', 'Can change, view their own album'), ('editor', 'Can change, view, edit, delete all albums'), ('viewer', 'can view content')]},
        ),
        migrations.RemoveField(
            model_name='musicmanageruser',
            name='role',
        ),
    ]
