# Generated by Django 5.1.2 on 2024-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_music_manager', '0002_alter_musicmanageruser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicmanageruser',
            options={'permissions': [('artist', 'Can view and change only their own album'), ('editor', 'Can view, change, add, and delete all albums'), ('viewer', 'can view albums')]},
        ),
    ]
